### ISSUE TITLE
Render summer toboggan and bobsleigh tracks

### ISSUE THREAD

**Issue by max-dn** [der-stefan/OpenTopoMap#106]
We have some attraction=summer_toboggan in the database. These objects are big, they are obstacles, landmarks and indications of touristic infrastructure in a landscape... There were some discussions about rendering them ([1](https://forum.openstreetmap.org/viewtopic.php?id=40329), [2](https://forum.openstreetmap.org/viewtopic.php?pid=646704#p646704)).

Same with bobsleigh tracks (leisure=track and sport=bobsleigh, maybe some surface tags...). 

I wonder how to render them... bobsleigh tracks are easy, they are icy blue and something like small roads ;) But I found no good rendering for toboggans with clear difference to roads... In reality they mostly are light gray structures made of concrete...

![toboggan V1](https://geo.dianacht.de/bilder/otm_toboggan_1_16.png)
Examble of a toboggan [near Durchholzen](http://www.openstreetmap.org/way/122734675#map=17/47.63618/12.28859) and a bobsleigh track near the [Königsee](http://www.openstreetmap.org/way/130658309#map=16/47.5889/12.9818)

**Comment by der-stefan** [comment]
Very nice! Let's do it! The summer toboggan guys will love it, because even the standard osm.org map style ignores them...

**Comment by der-stefan** [comment]
Do you already have a style ready for a pull request? (I guess so, because you did the screenshots...)

**Comment by max-dn** [comment]
Not yet. Not all zoom levels and I think, the tracks should be narrower. Labels are also missing.

Maybe a small pull request: We need attraction=* at the next update. (#108), the rest will follow soon ;)

**Comment by der-stefan** [comment]
Ok, no problem. If you like you can already commit it and I will add the missing zoom levels.
