### ISSUE TITLE
implement soccer fields

### ISSUE THREAD

**Issue by der-stefan** [der-stefan/OpenTopoMap#11]
similar to the German osm.de style

**Comment by der-stefan** [comment]
See #105

**Comment by der-stefan** [comment]
Done.

**Comment by der-stefan** [comment]
I would like to render leisure=pitch & sport=multi on zoom 13-14 the same as sport=soccer.

**Comment by max-dn** [comment]
Good idea. In my eyes the oval icon is even more "multi" than "soccer".

Two other issues with pitches:
* I think we are too restrictive with checks of the size of a basketball pitch. A lot of them seems to have the same size as other marked pitches, but are too large. We should als accept larger pitches, at least until [my pitch](https://opentopomap.org/#map=17/48.17633/11.72372) gets an icon ;)
* What about coloring the other unmarked pitches. We have now a darker green for pitches with icons than the other. Maybe we should use the same color... [discussion here](https://forum.openstreetmap.org/viewtopic.php?pid=654052#p654052)

**Comment by der-stefan** [comment]
Pitches with a tartan line should have a second outer line.

**Comment by der-stefan** [comment]
We need to check, if there is a line or polygon with leisure=track and sport=athletics embracing the sports field. If true, let's choose a different symbol.

**Comment by der-stefan** [comment]
There is a problem with the pitch function:
```
Mapnik datasource exception: Postgis Plugin: ERROR:  query "SELECT ST_ExteriorRing(ST_SimplifyPreserveTopology((st_dump(inway)).geom,100))" returned more than one row#012CONTEXT:  PL/pgSQL function getpitchicon(geometry,text) line 33 at assignment#012in executeQuery Full sql was: 'SELECT ST_AsBinary("way") AS geom,"angle","icon","labelsizefactor","pitch_area" FROM (SELECT way,(pitchdata).icon AS icon,(pitchdata).angle AS angle,(pitchdata).pitch_area AS pitch_area,(pitchdata).labelsizefactor AS labelsizefactor FROM (select way,getpitchicon(way,sport) as pitchdata FROM planet_osm_polygon WHERE leisure='pitch' AND (building IS NULL OR building = 'no')) AS pitches) AS symbols WHERE "way" && ST_SetSRID('BOX3D(973501.9922400019 6843865.76454154,1022421.690342518 6892785.462644055)'::box3d, 3857)'
```

**Comment by max-dn** [comment]
Very funny: Soccer fields as multipolygon consisting of two half pitches with a hole in the middle...
http://www.openstreetmap.org/relation/6758760
http://www.openstreetmap.org/relation/7370313
I will try to get a patch for these uncommon an creative cases ;)

**Comment by max-dn** [comment]
> We need to check, if there is a line or polygon with leisure=track and sport=athletics embracing the sports field. If true, let's choose a different symbol.

What should we do in Zoom>=16? There we have no oval symbol. Render the leisure=track (some are areas, like relation 3944876, some are lines like way 120170396)? Or create additional icons for "soccer with tartan arround it" (hard work)?

**Comment by der-stefan** [comment]
Yes, leisure=track should be shown in the same color like pitches: 8d26d9e
Example: https://opentopomap.org/#map=17/49.58079/11.01324

**Comment by max-dn** [comment]
Just to have something to look at: [Some soccer/multi](https://geo.dianacht.de/otmtest/soccertracks.html) with and without tracks around Erlangen, made with an [test version of pitchicon.sql](https://geo.dianacht.de/otmtest/pitchicon.sql.txt). It searches for surrounding tracks in 40m distance, I hope it finds all ;)
We use the same function for all zoom levels, so we unnecessary loose some time in Z17, because there we don't need the info about tracks. But I think it's ok, the average tile in Z17 doesn't contain any leisure=pitch...

**Comment by der-stefan** [comment]
Perfect! Thank you, @max-dn.
![sports-oval-track](https://user-images.githubusercontent.com/3618939/34012424-f9bf4fe6-e113-11e7-9909-8c74a768edd7.png)

**Comment by der-stefan** [comment]
Issue finally done. Thank you again, @max-dn!
