### ISSUE TITLE
HOWTO_DEM missing important information

### ISSUE THREAD

**Issue by alexandervlpl** [der-stefan/OpenTopoMap#118]
From HOWTO_DEM:

`# The new approach is to take the DEM and contours from opensnowmap`

`# Now import the contours e.g. from opensnowmap.`

So how do I actually do that? There's no information about this on OpenSnowMap. The "Old description (not verified)" section in the HOWTO does not sound very encouraging either. :smile: 

I realise that I can use GDAL tools to process ASTER, SRTM and other DEMs... but all these datasets have errors and voids that are (thankfully) not present in OpenTopoMap.

Can someone please provide details on how to obtain or generate the high quality contour layer currently used by OpenTopoMap? @der-stefan ?

Thanks in advance!

**Comment by m-dp** [comment]
The "Old description" does populate the database successfully. But, unless I made a mistake, it does not arrive to providing the view that contains the final fields 'wkb_geometry' and 'height'. Please see my "Issue" just posted.

**Comment by der-stefan** [comment]
See #120

**Comment by alexandervlpl** [comment]
Thanks for the info! So all the references to OpenSnowMap should be removed from the docs now?

**Comment by m-dp** [comment]
For what OpenSnowMap is concerned, I make reference to http://blog.opensnowmap.org/post/2016/08/23/Opensnowmap-Tile-Usage-Policy (I stopped there). 
For what obtaining the hillshading and contours is concerned, the instructions work well, /provided/ you access the database differently, as I showed in the other post. 

As you read, I am encouraging Stefan to fix the gap between the outcomes of the instructions and the database query he uses in the mapnik map definition xml.

**Comment by wima75** [comment]
whats the status about this? Can the contours from OpenSnowMap imported or not? How to do that?
Thank you.

**Comment by der-stefan** [comment]
I removed the note about opensnowmap, as their contours data is not public due to its size (you don't want to share a file with ~300 GB even in 2018!).
If you stick to the HOWTO_DEM, you can create your own contour lines and DEM geotiff quite straight forward. We changed our database, so it is compliant with the format by osm2pgsql. Just edit opentopomap.xml in layer "contours" as noted there.

**Comment by der-stefan** [comment]
Is it clear now with all the new Howtos? I am closing the issue, please reopen if necessary.
