### ISSUE TITLE
Relation contours does not exist

### ISSUE THREAD

**Issue by m-dp** [der-stefan/OpenTopoMap#120]
I created an OTM server: everything works but the contours. I followed the HOWTO_DEM, "old description" section (as the recommended "opensnowmaps" are not available). 
A 'contour' database is created; it is populated with many GB of data, the source being .hgt files from www.imagico.de, as per the instructions. 

The problem is: the query 
SELECT wkb_geometry,height FROM contours
of opentopomap.xml (section: Layer name="contours") does not work: the 'contours' database does not contain a 'contours' table. A query returns 
ERROR:  relation "contours" does not exist

The HOWTO_DEM is probably missing a piece. The data is there; how to complete the process so that the query in opentopomap.xml works?

**Comment by m-dp** [comment]
I obtained displaying the contours in the rendered map by replacing with the query 
(SELECT way,ele AS height FROM planet_osm_line) AS contours 
the original non-working query '(SELECT wkb_geometry,height FROM contours) AS contours' in opentopomap.xml

**Comment by der-stefan** [comment]
If you want to find out, how your table look like, try this:
```
$ psql contours -c "\d"
                 List of relations
 Schema |         Name         |   Type   |  Owner  
--------+----------------------+----------+---------
 public | contours             | table    | otmuser
 public | contours_ogc_fid_seq | sequence | otmuser
 public | geography_columns    | view     | otmuser
 public | geometry_columns     | view     | otmuser
 public | raster_columns       | view     | otmuser
 public | raster_overviews     | view     | otmuser
 public | spatial_ref_sys      | table    | otmuser
(7 rows)
```
And then if your table is called contours and you want to find out about columns and data types:
```
$ psql contours -c "\d contours"
```
Don't mix up database and table names. They can be identical, but don't need to.

**Comment by m-dp** [comment]
Thank you Stefan, 
in fact the database contains the following: 

```
postgres@m1:~$ psql contours -c "\d"
              List of relations
 Schema |        Name        | Type  | Owner 
--------+--------------------+-------+-------
 public | geography_columns  | view  | op
 public | geometry_columns   | view  | op
 public | planet_osm_line    | table | op
 public | planet_osm_nodes   | table | op
 public | planet_osm_point   | table | op
 public | planet_osm_polygon | table | op
 public | planet_osm_rels    | table | op
 public | planet_osm_roads   | table | op
 public | planet_osm_ways    | table | op
 public | spatial_ref_sys    | table | op
(10 rows)
```
As you can see, the database 'contours', obtained through the instructions in HOWTO_DEM (old description), does not contain a table 'contours'. _But a table 'contours' is required in your opentopomap.xml_, by the query 
SELECT wkb_geometry,height FROM contours 
. 
So, we are left wondering, how you obtained that database above in your post, containing tables 'contours', 'contours_ogc_fid_seq' etc. 

I wish to suggest that you update the HOWTO_DEM, since the "new approach" section is outdated (no more data available in opensnowmaps) and apparently not complete (no command to populate the contours database is specified), while the "old description" section does populate the contours database but does not complete the job (no 'contours' table is produced in the 'contours' database). 

To my best guess, your 'contours' table (columns: wkb_geometry,height) is akin to my 'planet_osm_line' table (way,ele). I looked for data akin to the height matchable with data of type "geometry", and it worked. But it is certainly not what you intended, and it can be confusing for users. 

```
postgres@m1:~$ psql contours -c "\d planet_osm_line" 
          Table "public.planet_osm_line"
  Column  |           Type            | Modifiers 
----------+---------------------------+-----------
 osm_id   | bigint                    | 
 ele      | integer                   | 
 way_area | real                      | 
 way      | geometry(LineString,3857) | 
Indexes:
    "planet_osm_line_index" gist (way)
    "planet_osm_line_pkey" btree (osm_id)
```

**Comment by m-dp** [comment]
About browsing the database: together with the command line (examples above), it is worth recommending also **adminer**: a PHP based database browser that consists _of a single file_. Since the gis servers are webservers, it is very fast and comfortable to add adminer.php to the web documents.

**Comment by der-stefan** [comment]
See issue #118. There is a note about that in opentopomap.xml now.
Should finally be clear now, right? ;-)
