### ISSUE TITLE
Colorful tourist tracks

### ISSUE THREAD

**Issue by myneur** [der-stefan/OpenTopoMap#123]
The map style is awesome, but marked tourist tracks are missing. These are essential for hikers navigation. 
[Example of map with tourist trails](https://en.mapy.cz/turisticka?x=8.2482570&y=48.5637300&z=15&l=0) and same [OpenTopoMap without](https://opentopomap.org/#map=15/48.56411/8.24833). 

Could you add colorful tourist tracks to the style? The tracks tagged by [osmc:symbol](http://wiki.openstreetmap.org/wiki/Key:osmc:symbol). The first word before ":" is the color. 

That will push the map readability for hikers to the next level. 
Thanks

**Comment by severak** [comment]
BTW - openstreetmap.cz [can display this](https://openstreetmap.cz/#map=14/49.8517/14.2494&layers=uK) via an overlay

**Comment by myneur** [comment]
That overlay is awesome! Exactly how it should look like. Can it be added to the Garmin map export?

**Comment by severak** [comment]
@myneur that overlay is only for webmaps.

**Comment by der-stefan** [comment]
You can enable hiking and biking overlays from http://waymarkedtrails.org/
Rendering those overlays is not part of OpenTopoMap.

**Comment by myneur** [comment]
@der-stefan that does not work for Garmin export, so I can not see it on a Garmin device. 

Also note that waymarkedtrails.org style is pretty hard to read. The openstreetmap.cz mentioned above is much better. 

I personally consider a hiking map without hiking trails useless.

**Comment by mboeringa** [comment]
> I personally consider a hiking map without hiking trails useless.

The map is called "Open-**_Topo_**-Map", not "OpenHikingMap". I guess @der-stefan has other goals with his map...

**Comment by myneur** [comment]
@mboeringa so what is a purpose of this map if not hiking (or biking or skiing)? What is this map intended to be used for?

**Comment by mboeringa** [comment]
Well, of course, you have to ask @der-stefan , not me.

But other than that, i don't agree with your remark that:

_"a hiking map without hiking trails is useless."_

I have used topographic maps in both Great Britain and the Netherlands for basic hiking experiences and orientation. Using signage on guideposts and place names, you can set out your own route.

**Comment by der-stefan** [comment]
@myneur Yeah, the hiking overlays from openstreetmap.cz are really nice. They are from poloha.net (example: https://tile.poloha.net/kct/13/4397/2797.png)
Unfortunately they are limited to CZ.

The map style by mapy.cz is awsome! Very well made mapserver style!

**Comment by myneur** [comment]
@der-stefan yep, and they don't have an export to a Garmin device, so it's not possible to use it... 
I consider the marked trails the most important feature in every map, because the marked track guides you this is a prefered or even an interesting route to take. 
For that reason e.g. mapy.cz prefer the marked routes in their hiking route-planner to the shorter track. It also helps the navigation even if you have a track in the watch: e.g. here I'll continue on the red track and on the next turn, I'll change to a blue track.
