### ISSUE TITLE
Access-Control-Allow-Origin Header to enable client-side caching

### ISSUE THREAD

**Issue by brotkiste** [der-stefan/OpenTopoMap#124]
Hi, thanks for this amazing app!
I'd like to enable client-side caching using [Leaflet.TileLayer.PouchDBCached
](https://github.com/MazeMap/Leaflet.TileLayer.PouchDBCached)
This requires the the Access-Control-Allow-Origin Header to be set to 
`Access-Control-Allow-Origin: *`
Is this something you could do? This would decrease network usage of my app as well as load on the opentopomap.org tileserver as only cached tiles older than e.g. 24h are refreshed. (Only visited tiles are cached)
Schönes Wochenende :)

**Comment by der-stefan** [comment]
Let's see how to get that working with Apache.

**Comment by brotkiste** [comment]
I think this could work : [https://enable-cors.org/server_apache.html](https://enable-cors.org/server_apache.html)

I'm currently using this as a workaround: [https://github.com/Rob--W/cors-anywhere](https://github.com/Rob--W/cors-anywhere)

**Comment by brotkiste** [comment]
Vielen Dank :)

**Comment by geo903** [comment]
Not enough headers CORS ((the proxy is very slow

**Comment by der-stefan** [comment]
Fixed for backup tile server 09/2018.

**Comment by der-stefan** [comment]
...and fixed again for the main server.
