### ISSUE TITLE
Make sure all the tiles for all zoom levels of a particular area are synchronized

### ISSUE THREAD

**Issue by jidanni** [der-stefan/OpenTopoMap#126]
There is a cell tower at
https://opentopomap.org/#marker=15/24.15768/120.86510

But when I zoom to the next level, it disappears!

I would make sure all the tiles for all zoom levels of a particular area are synchronized.

It is OK to have old tiles, just be sure they are old for all layers.

**Comment by der-stefan** [comment]
It will be fixed with the next update - please hang on for a few days.
It is not possible to guarantee that all zoom levels are synchronized. The renderer decides on its own when to update the tiles.
