### ISSUE TITLE
Viewpoint hedgehogs

### ISSUE THREAD

**Issue by der-stefan** [der-stefan/OpenTopoMap#128]
When there are too many viewpoints, the map looks ugly:
![viewpoints](https://user-images.githubusercontent.com/3618939/32967419-e8a8dc68-cbdd-11e7-8521-e5e787b37995.png)

There are two options how to improve:
- Thin out the viewpoints by calculating the minimum distance to the next viewpoint.
- Only render viewpoints with direction!=NULL

I prefer the second option.

**Comment by max-dn** [comment]
How about a compromise? Rendering of viewpoints without direction with smaller hedgehogs?

**Comment by der-stefan** [comment]
Only showing viewpoints with direction!=NULL:
![viewpoints_verbessert](https://user-images.githubusercontent.com/3618939/33230390-e551ef22-d1e2-11e7-9ce9-60966fff463a.png)

That's how I like it. Let's try the radical way!
