### ISSUE TITLE
Howto generate garmin maps of currently uncovered areas

### ISSUE THREAD

**Issue by hamburger1984** [der-stefan/OpenTopoMap#142]
Hi!
Thanks for this wonderful project. I really like the map (online as well as on a garmin device). I get, that you're currently not ready to extend the generation of garmin maps to further areas.

Could you give some hints on how to generate garmin maps for custom areas?

Cheers,
  Andreas

**Comment by hamburger1984** [comment]
Added a simple walk through. Basically the results of my attempts to follow the HOWTO. Maybe this is useful for the next one willing to generate a garmin map.

**Comment by der-stefan** [comment]
Thank you very much, @hamburger1984 !
