### ISSUE TITLE
say http**s** and add a GetCapabilities link.

### ISSUE THREAD

**Issue by jidanni** [der-stefan/OpenTopoMap#145]
​On https://opentopomap.org/about
say
`<abbr title="also z.B. http`****s****`://a.tile.opentopomap.org/14/8695/5583.png">{a|b|c}.tile.opentopomap.org/{z}/{x}/{y}.png</abbr>`

Also add a GetCapabilities link.  

See https://josm.openstreetmap.de/ticket/15930 .

**Comment by der-stefan** [comment]
Thanks, fixed.
