### ISSUE TITLE
Magnifying Glass

### ISSUE THREAD

**Issue by max-dn** [der-stefan/OpenTopoMap#146]
I found i[n the forum](https://forum.openstreetmap.org/viewtopic.php?pid=686700#p686700) a link to [bbecquet/Leaflet.MagnifyingGlass](https://github.com/bbecquet/Leaflet.MagnifyingGlass). Cool idea, perhaps something for OTM, sometimes ...

**Comment by der-stefan** [comment]
Hm, ok, I think it is not a tool, but just a nice toy. I wouldn't add it to our web interface.

**Comment by der-stefan** [comment]
If you don't mind, I will close the issue. I'm not a fan of the magnifying glass for our OTM web interface...
