### ISSUE TITLE
hillshade-30m-jpeg.tif missing

### ISSUE THREAD

**Issue by wima75** [der-stefan/OpenTopoMap#147]
Hi
I'm missing the file referenced here: https://github.com/der-stefan/OpenTopoMap/blob/master/mapnik/styles-otm/hillshade.xml#L61
How can I generate that?
Thank you

**Comment by der-stefan** [comment]
There is a completely new Howto here:
https://github.com/der-stefan/OpenTopoMap/blob/master/HowToForDummies.md
