### ISSUE TITLE
Durchgestrichene Höhenangaben

### ISSUE THREAD

**Issue by chatelao** [der-stefan/OpenTopoMap#150]
Die Höhenangaben auf den Höhenlinien sind durchgestrichen.

Wäre es möglich, die Höhenlinien für die Breite der Höhenangabe zu unterbrechen?

**Comment by max-dn** [comment]
> Wäre es möglich, die Höhenlinien für die Breite der Höhenangabe zu unterbrechen?

hmmm... Üblicherweise regelt man das über einen hellen Saum (mapnik nennt das "halo") um die Buchstaben. Der ist bei den Höhenlinien recht dünn (1 Pixel) und hat nur geringe Deckkraft (30%). Wird der dominanter gemacht, siehts auf der hellen Seite der Berge ganz ok aus, auf den dunklen Hängen wirds dafür richtig hässlich:

![Contour](https://geo.dianacht.de/bilder/otm_contour_helo.png)
(bisschen übertrieben, halo mit 3px und 100% Deckkraft)

Wird schwierig da nen Kompromiss zu finden...

**Comment by der-stefan** [comment]
Den Kompromiss hatte ich damals schon versucht zu finden. Lieber bisschen mehr durchgestrichen, dafür nicht ganz so auffällig weiß im Hochgebirge. Ebenfalls ein Dorn im Auge ist es, dass man trotz entsprechender Mapnik-Option keine auf dem Kopf stehenden Label platzieren kann.

Das Problem ist das gleiche wie in #9. Leider bietet Mapnik nicht von Haus aus an, comp-ops zwischen definierten Ebenen anzuwenden (siehe http://mapnik.org/news/2012/04/20/smart-halos/).

Deshalb schließe ich die Fehlermeldung wieder und verweise auf #9, das offen bleibt.

**Comment by chatelao** [comment]
Danke für die detaillierten Erläuterungen.
