### ISSUE TITLE
viewfinderpanoramas.org/dem3/M32.zip --> Forbidden

### ISSUE THREAD

**Issue by guillaumebof** [der-stefan/OpenTopoMap#163]
i'm trying to build a OTM server and get this issue : i can't download the files from viewfinderpanoramas.org because of :
You don't have permission to access /dem3/ on this server.
is there another place to get them ?
thanks a lot
guillaume

**Comment by max-dn** [comment]
I used http://www.imagico.de/map/demsearch.php to get a list of DEM files and downloaded them. I also get a "don't have permission to access /dem3/" when I tried to access www.viewfinderpanoramas.org/dem3/ but the access to the listed files (e.g. www.viewfinderpanoramas.org/dem3/L32.zip ) works.

**Comment by guillaumebof** [comment]
thanks a lot, a mistake of mine
