### ISSUE TITLE
isolation.c

### ISSUE THREAD

**Issue by Roburetto** [der-stefan/OpenTopoMap#169]
There are surprisingly few solutions to calculate topographic isolation. I have been trying to use isolation.c but have a few doubts:

- Is it suitable to calculate isolation at regional level or must a worldwide DEM always be used? Also, is it indifferent if the DEM units are in meters or in feet?
- I reckon the input peaks csv must be defined with stdin=/path/to/csvfile.csv prior to running isolation. Is this correct?
- I suppose this warning during compilation can be ignored?
```
@debian:~/Documents$ cc -Wall -o isolation isolation.c -lgdal -lm -O2
isolation.c: In function ‘get_height’:
isolation.c:103:2: warning: ignoring return value of ‘GDALRasterIO’, declared with attribute warn_unused_result [-Wunused-result]
  GDALRasterIO(hBand,GF_Read,xpx,ypx,2,2,area2x2,2,2,GDT_Int16,0,0);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
isolation.c: In function ‘get_isolation_by_DEM’:
isolation.c:187:3: warning: ignoring return value of ‘GDALRasterIO’, declared with attribute warn_unused_result [-Wunused-result]
   GDALRasterIO(hBand,GF_Read,le,up,w,h,DEMarea,w,h,GDT_Int16,0,0);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

It turns out, that if I run something like:
/home/user/Documents/isolation -f /home/user/Documents/DEM.tif -d 4 -o csv

I just get in return:

```
0 Reading /home/user/Documents/DEM.tif 3430px x 6493px x 1 band
Origin =(-9.608476,42.189577) Pixel Size=(0.001051,-0.000808)
ERROR 5: /home/user/Documents/DEM.tif, band 1: Access window out of range in RasterIO().  Requested
(9141,52237) of size 2x2 on raster of 3430x6493.
  Getting x/y:9141 52237 at -0.000044 0.000097 h=-5272 20112 32636 0
Input: 
 -> ele: id=0 lon=0.000000 lat=0.000000 ele=32636.000000
ERROR 5: /home/user/Documents/DEM.tif, band 1: Access window out of range in RasterIO().  Requested
(9141,52237) of size 2x2 on raster of 3430x6493.
  Getting x/y:9141 52237 at -0.000044 0.000097 h=0 0 0 0
Input: 
 -> ele: id=0 lon=0.000000 lat=0.000000 ele=0.000000
```

If possible, would appreciate any help understanding what's wrong. Thanks.

**Comment by max-dn** [comment]
> Is it suitable to calculate isolation at regional level or must a worldwide DEM always be used? Also, is it indifferent if the DEM units are in meters or in feet?

A regional DEM should work, I just tried it with two different regions in different resolutions. The program is searching the next higher point in a radius of "-r" or 100km. So your DEM should cover a region of 100km around the peak (if not, you get wrong isolations for mountains at the border of your area).
The program tries to convert "100 ft" in "30.48" (Line 78). So if you use units in your input data, it will be converted and your DEM must be in meters. If you don't have units in your input data, your DEM only has to be in the same unit.

> I reckon the input peaks csv must be defined with stdin=/path/to/csvfile.csv prior to running isolation. Is this correct?

I do it with a pipe "cat input.csv | isolation ..." so the input is the stdin. But thats on a linux system, didn't try it on a windows.

> I suppose this warning during compilation can be ignored?

I think so. GDALRasterIO() is defined with a return value, but we don't use ist.

> t turns out, that if I run something like:

this 
> id=0 lon=0.000000 lat=0.000000 ele=0.000000

seems to be strange... 

I think your input is incorrect (or can't be read at all...). You open a DEM (left corner at W9.60°, pixel size=0.001051, width=3430, that means right corner is at W9.60°-0.001051*3430=W6°) and try to calculate a peak at 0°. That's far east of your area at pixel 9141 (you have only 3430) and that is a "window out of range". This error is from Line 103, what means, that also the ele of this peak is unknown or not parseable and also not the lat and lon (both are 0)

So I think your  only problem is the reading of a input file ... ;)

To start you could try it with a csv of some peaks in your area 
1260545854;-8.8349402;41.9684856;\
5584339555;-8.7147352;41.9216037;638\
3744854483;-8.0410709;41.8248506;1548\
5584339531;-8.2918744;41.9294428;1416

should lead to 
3744854483;-8.0410709;41.8248506;61848\
5584339555;-8.7147352;41.9216037;9025\
5584339531;-8.2918744;41.9294428;22032\
1260545854;-8.8349402;41.9684856;403

If you don't want to calculate the isolations, you also may download [a weekly generated list](https://geo.dianacht.de/topo/topographic_isolation_viefinderpanoramas.txt) of osm_id;lon;lat;isolation

**Comment by Roburetto** [comment]
Thanks for you help. 

It was a problem with the way the input was being defined.

This seems to be working:
`cat /home/user/Documents/input.csv | /home/user/Documents/isolation -f /home/user/Documents/DEM.tif -o csv > output.csv`
