### ISSUE TITLE
Some ideas about natural areas

### ISSUE THREAD

**Issue by max-dn** [der-stefan/OpenTopoMap#170]
I collect some ideas on how we could render mountain regions and natural areas. After the next update we have region:type in the database (#164)

What else belongs to this group? We have

* region:type = mountain_area (as area)
* region:type = natural_area (as area)
* natural = massif (as area)
* natural = mountain_range (as area and line)
* natural = valley (as area and line)
* natural = couloir (as line)
* natural = ridge (as line)
* natural = arete (as line)
* something I didn't see? Maybe because I am too focused to alpine regions?

Not all of this is defined in the wiki, but it exists in our database e.g. natural = valley as area and natural = arete is also used for normal valleys.

For processing, I would build something, which analyses the location and the size of the areas. [The Alps](https://www.openstreetmap.org/relation/2698607) have a size of  3.7e + 11 units, its largest subgroup are the [Lavanttaler Alpen](https://www.openstreetmap.org/relation/2451118) with 1.2e + 10. We should hide the label for the Alps, when we show the Lavanttaler Alpen.

For rendering I would use the existing style for valleys and mountains. In [areas with many natural = ridges and natural = valleys](https://opentopomap.org/#map=13/46.41017/13.92543) it looks pretty good.

**Comment by max-dn** [comment]
Just to show where I want to go to: These are all areas and lines mentioned above. The labels are calculated with an algorithm similar to the labels of lakes, but I try to avoid horizontal lines.

![Alps](https://geo.dianacht.de/bilder/otm_natarea_alpen_1.png)

We also render natural=valleys which are mapped as areas, so [Valle di Sasso Bisòlo](https://www.openstreetmap.org/way/292871472#map=14/46.2164/9.6680)  is shown and also [Valle di Preda Rossa](https://www.openstreetmap.org/way/253118274), which is a area.

![Bergell](https://geo.dianacht.de/bilder/otm_natarea_bergell_1.png)
([this region](https://opentopomap.org/#map=13/46.24867/9.65338) and of course the "rgel"-rest of "Bergell" shoud disapear in that zoom level)

**Comment by der-stefan** [comment]
Wow, this looks great! If you smooth some lines and don't put labels on straight lines, this will be even greater!

**Comment by max-dn** [comment]
The first try now is a segment of a circle through the area (if you see straight lines, they are segments of very large circles...):
![Alpen 2](https://geo.dianacht.de/bilder/otm_natarea_alpen_2.png)

the fallback for areas which can't be covered with a segment is still the same as before, like for "Rofangebirge" above (center, upper third) or the "Kaunergrat" here:
![Kaunergrat](https://geo.dianacht.de/bilder/otm_natarea_kaunergrat_2.png)

Should we do smoothing for lines? Some of the valleys [are smooth enough](https://www.openstreetmap.org/way/408024079#map=11/46.8991/11.5233), [some are not](https://www.openstreetmap.org/way/405649179#map=13/47.5841/12.2384)...

**Comment by max-dn** [comment]
Iw𝑙l need some days... I have still problems with [strange shaped areas](https://www.openstreetmap.org/relation/253825#map=10/42.0936/23.4489) and i want to do some tests what to show in which zoom level. At least to give a hint for rendering.

**Comment by mboeringa** [comment]
> I will need some days... I have still problems with [strange shaped areas](https://www.openstreetmap.org/relation/253825#map=10/42.0936/23.4489) and i want to do some tests what to show in which zoom level. At least to give a hint for rendering.

I wouldn't bother to much with that particular shape. While maybe an interesting test case, this is clearly wrong tagging: what seems to have happened here is that someone took the outline of a now defunct landuse=forest multipolygon, now superseded by more detailed forestry tagging, and just slapped mountain range tagging on it without regard for the real outlines of the range. As a consequence, if we have to believe this feature, the highest peaks are actually not part of the range, as they aren't incorporated in the former landuse=forest MP but are excluded by the "inners" representing the highest ridges above the tree line and thus devoid of trees.

See the wikipedia article about the Rila mountain range for a map that more clearly shows the range:
https://en.wikipedia.org/wiki/Rila

Looking at the object's history, confirmed my suspicion and indeed reveals its history as a forest feature:
https://www.openstreetmap.org/relation/253825/history#map=11/42.1110/23.5316&layers=C

**Comment by max-dn** [comment]
Reminder for myself: For the sake of completeness, we should also show **natural=gorge**. But first let's see, what we have to change after we saw this on a map...

**Comment by max-dn** [comment]
I'm not happy with the regions yet. I think the label covers too many more important things like peaks.

I tried to label the areas last and let mapnik search for free space. Thats mostly ok, mapnik is smart enough. Sometimes that doesn't work and the label moves to the edge of an area or covers just a small part in the center of a large region...

![civetta](https://geo.dianacht.de/bilder/otm_natarea_overlap_civetta.png)
[here](https://opentopomap.org/#map=12/46.3585/12.0570) the label is ok

![arnspitz](https://geo.dianacht.de/bilder/otm_natarea_overlap_arnspitz.png)
[here](https://opentopomap.org/#map=13/47.38929/11.21524) the label is too far at the edge, but you see the summits...

![tauern](https://geo.dianacht.de/bilder/otm_natarea_overlap_tauern.png)
[here](https://opentopomap.org/#map=8/46.8715/12.7084) you see the Großglockner, but someone could thing the "Hohe Tauern" is only the area east of this summit.

Another approach would be a transparent label that can be overridden (like in [freemap.sk](https://www.freemap.sk/?map=11/48.772030/20.552330&layers=T) or [dianacht.de](https://geo.dianacht.de/topo/?zoom=10&lat=47.42713&lon=11.38464)). But this works only with big characters (large areas with short names in high zoom levels) and I think this labels don't fit to the current style with its strong contrasts and the small fonts:
![arnspitz](https://geo.dianacht.de/bilder/otm_natarea_transparent_arnspitz.png)

**Comment by der-stefan** [comment]
Thanks, @max-dn for your explanation. As you already suggested, transparent labels don't fit well in our map style. In my opinion region labels are more important than single peak names.
I think Mapnik can be told to place the letters over the whole line instead of placing them on one side only.

**Comment by mboeringa** [comment]
> In my opinion region labels are more important than single peak names.

Agree, and at scales that peak names become truly important (larger than 1:50k), it usually does not make sense to render region names, as a single map view will only cover a small portion of the region.
