### ISSUE TITLE
waterway-lines Filter Typo

### ISSUE THREAD

**Issue by knowname** [der-stefan/OpenTopoMap#177]
https://github.com/der-stefan/OpenTopoMap/blob/30e444a7d2012937d5ec46aa179f493e501b4208/mapnik/styles-otm/waterway-lines.xml#L91

i assume the second 'VIb' is meant to be 'VIc'.

Same thing in https://github.com/der-stefan/OpenTopoMap/blob/30e444a7d2012937d5ec46aa179f493e501b4208/mapnik/styles-otm/waterway-lines.xml#L98

**Comment by der-stefan** [comment]
Thank you, @knowname . This was a hard-to-find-bug.
