### ISSUE TITLE
The underground part of the rivers is drawn as above-ground

### ISSUE THREAD

**Issue by pgavrilov** [der-stefan/OpenTopoMap#178]
The underground part of the rivers is drawn as above-ground.

Example:
OpenStreetMap:
https://www.openstreetmap.org/#map=17/55.87349/37.49825
![openstreet](https://user-images.githubusercontent.com/3817702/43190748-66049e52-9002-11e8-9546-d47e360873e2.jpg)
OpenTopoMap:
https://opentopomap.org/#map=17/55.87349/37.49825
![opentopo](https://user-images.githubusercontent.com/3817702/43190750-6643d5fe-9002-11e8-9996-ecc11859b9b7.jpg)

**Comment by max-dn** [comment]
Yes, we have underground streams and ditches and minor canals (CEMT< IV) , but forgot tunneled canals and streams. I will try to show them and maybe also tunnel=culvert (now we only have tunnel=yes).

**Comment by der-stefan** [comment]
Thank you @pgavrilov for reporting and @max-dn for fixing the issue!
