### ISSUE TITLE
The OpenTopoMap/mapnik/relief.txt file does not exist

### ISSUE THREAD

**Issue by timautin** [der-stefan/OpenTopoMap#182]
Hello,

The file "OpenTopoMap/mapnik/relief.txt", used in the HowToForDummies at the step "Create color relief for different zoom level" no longer exists. Could you provide it / update the how-to?

Thanks!

**Comment by max-dn** [comment]
relief.txt was renamed to relief_color_text_file.txt in June and deleted some weeks later. I restored it and corrected the HowToForDummies...

The content of relief.txt was
```0 0 0 0 0
1     17 120   3
100   72 162  69
300  231 218 158
1500 161  67   0
3000 130  30  30
4000 110 110 110
5000 255 255 255
6000 255 255 255
```

**Comment by timautin** [comment]
Thanks a lot man!
