### ISSUE TITLE
Performance on query for "symbols-peaks" layer

### ISSUE THREAD

**Issue by hottrails** [der-stefan/OpenTopoMap#188]
In my installation I realized that when going from zooming in level by level the level 13 was rendered significantly slower than e.g. level 12 and 14.

In Postgresql logsl I found that the query for "symbols-peak" layer took nearly 3 seconds. As there is no WHERE clause all planet_osm_point entries in the specific area are returned by the query, most of them unneeded as only few actually are peaks. 

Adding **WHERE ("natural" = 'peak' or "natural" = 'volcano')** (those attributes that are evaluated in symbols-peaks.xml) to the SQL made the  rendering as fast as on the other levels

**Comment by der-stefan** [comment]
Wow, that's great! We did some tests regarding rendering speed of each zoom level some time ago, but this was new. And I thought that Mapnik automatically optimizes the inner and outer SQL queries in exactly this way. Perhaps this doesn't work with the column "natural" due to the quotation marks?
Anyway - thank you, we implemented it.

**Comment by hottrails** [comment]
> And I thought that Mapnik automatically optimizes the inner and outer SQL queries in exactly this way.

I reviewed some SQL queries that I noted down during setup of my instance and think that mapnik isn't doing that at all. 

At that time I identified other bottlenecks, e.g. 
`SELECT way,way_area,landuse,leisure,"natural",wetland,leaf_type,amenity,crop,orchard FROM planet_osm_polygon ORDER BY (CASE WHEN landuse='forest' THEN 0 ELSE 1 END) asc) AS landuse`
performed 4 times faster when changed to 
`SELECT way,way_area,landuse,leisure,"natural",wetland,leaf_type,amenity,crop,orchard FROM planet_osm_polygon WHERE (not landuse is null) OR (not leisure is null) OR (not "natural" is null) OR (not wetland is null) OR (not amenity is null) ORDER BY (CASE WHEN landuse='forest' THEN 0 ELSE 1 END) asc) AS landuse`

Anyway opentopomap doesn't seem to have a big problem with rendering speed. Maybe the opentopomap situation may be different due to other system and database configuration & size. If you see further potential in query optimization please give me a hint if I can help.
