### ISSUE TITLE
Screen goes blank at last zoom level + 1

### ISSUE THREAD

**Issue by jidanni** [der-stefan/OpenTopoMap#190]
1. Go to https://opentopomap.org/#map=16/24.19805/120.80394
2. Now roll the mouse as if to zoom in even further.
3. The screen goes blank.

Yes, the + in the upper left corner was grey, preventing us from clicking it.
But you forgot to also prevent us from scrolling the mouse.

**Comment by der-stefan** [comment]
Are you sure? I can't reproduce that bug. I suppose that the zoom 17 tiles were not rendered yet at the time you tested it. Our tile server may need seconds to days to render specific tiles.

**Comment by jidanni** [comment]
OK I can't reproduce it today too, due to the
```
Main server is down due to upgrade. Only zoom 1-14 are available.
```

So maybe try again when that upgrade is over.

**Comment by der-stefan** [comment]
Oh yes, currently it is not possible ;-)
Please be patient, since I had trouble reinstalling the main server yesterday - and won't have much time in the next 2-3 weeks. At least my favorite zoom level 14 is still available online...

**Comment by der-stefan** [comment]
Renderer is still offline - but I'll close that issue now, see #192 for more details on the server status.
