### ISSUE TITLE
contour lines are wrong in browsers

### ISSUE THREAD

**Issue by GitHubNorb** [der-stefan/OpenTopoMap#191]
The contour lines are wrong in browsers. Examples:
a) https://opentopomap.org/#map=17/32.74175/-17.15114  Levadas on Madeira are nearly horizontal. The water flows slowly.
b) https://opentopomap.org/#map=16/51.22712/7.12888   Sambatrasse. Railways are learly horizontal. 
c) https://opentopomap.org/#map=17/51.15950/7.13605   Railways are learly horizontal. The river Wupper flows slowly.
Best regards
Norbert

**Comment by max-dn** [comment]
The contour lines are derived from [NASA SRTM](https://en.wikipedia.org/wiki/Shuttle_Radar_Topography_Mission) data. The are not very exact, at some places wrong and at some places missing, but we don't have better elevation data. There are some countries or states with free and open elevation data ([some are collected here](http://data.opendataportal.at/dataset/dtm-germany)), but the OpenTopoMap needs one data set for the whole world...

**Comment by der-stefan** [comment]
As @max-dn proclaimed, we don't manipulate contour lines and the digital elevation model (DEM) by hand. Unfortunately there is no Open Source project yet that corrects obvious errors (like your Wupper example). And for doing this on our own, we just don't have time and ambitions.
