### ISSUE TITLE
broken link on website https://opentopomap.org/about

### ISSUE THREAD

**Issue by funkes** [der-stefan/OpenTopoMap#198]
On website https://opentopomap.org/about I find the headline "Häufig gestellte Fragen", bullet no. 8 and the question "Ich habe einen Fehler in der Karte gefunden! Könnt ihr diesen korrigieren?". The answer shows a link labeled by "www.openstreetmap.org". This links points to "https://opentopomap.org/www.openstreetmap.org", but the opened window shows an error message "Not Found; The requested URL /www.openstreetmap.org was not found on this server."

**Comment by der-stefan** [comment]
Thank you - fixed. It would be great to have a CMS and a community that translates our website.
