### ISSUE TITLE
Support max zoom level higher than 16

### ISSUE THREAD

**Issue by henningvs** [der-stefan/OpenTopoMap#20]
By using the map made available on http://opentopomap.org/ and using the tiles in my own project, I noticed that the max tile level is at the moment level 16. 

The other tile sources I am using are generating tiles up to level 18, but opentopomap is just generating blue map tiles (like this one http://tile.opentopomap.org/18/140753/87758.png). 
So what I wanted to ask, is if it is possible to extend the zoom level to level 18 or at least give out an error (404 maybe)  if the zoom level my browser is asking for, is not available so I can handle this error adequately.

**Comment by der-stefan** [comment]
The problem is that mod_tile has a hard-coded max zoom of 20, so you need to change that before compilation.
We are planning more zoom levels for the future. But when and how - noone knows.

**Comment by henningvs** [comment]
This sounds promising. So what are the problems with supporting more zoom levels at the moment? Can I help to fix them?

**Comment by der-stefan** [comment]
The problem is our disk space. So the next step will be worldwide coverage. Let's see, how much space is left and then decide about the introduction of zoom level 17.

**Comment by der-stefan** [comment]
The future release (branch 2.0) will include a zoom level 17.

**Comment by der-stefan** [comment]
A preview of the 2.0 version can be found at http://dev.opentopomap.org
