### ISSUE TITLE
json file for taginfo

### ISSUE THREAD

**Issue by max-dn** [der-stefan/OpenTopoMap#211]
Should we create a json file for [taginfo](https://taginfo.openstreetmap.org/)?
I made a ugly [perl script](https://geo.dianacht.de/otmtest/maketaginfo_pl.txt), which parses opentopomap.xml and all included style files and creates a [json file](https://geo.dianacht.de/otmtest/taginfo.json), alternatively a [text output](https://geo.dianacht.de/otmtest/taginfo.txt) with most of the tags we use.

You don't get all tag automatically, because some of them are hidden in preprocessing or are only used in sql queries (layer=* for example). But these are only a few and we can list them by hand.
You also don't get all combinations of key/value, because some values are only used in negations (building is null) or comparitions (voltage &ge; 10000). But we mention all keys we use and hopefully most of the values.
So it's not perfect but better than nothing ... ;)

We could run this script after changes, commit it and let the json file on github. A lot of other projects have their file on raw.githubusercontent.com/.../taginfo.json.

**Comment by der-stefan** [comment]
Wow, your script is great! Let's use it!
Perhaps we could extend it for a automatically generated map legend?

**Comment by max-dn** [comment]
automatically generated map legend would be nice, but I don't know how to get images from this list... 

I will integrate this into taginfo after merge and hope my json is valid (my validators say it is...)

**Comment by max-dn** [comment]
[We are listed in taginfo](https://taginfo.openstreetmap.org/projects/opentopomap#tags) and I'm closing this issue. I will keep in mind map automatic key generation...
