### ISSUE TITLE
Rendering of railway=light_rail

### ISSUE THREAD

**Issue by simon04** [der-stefan/OpenTopoMap#22]
It seems that `railway=light_rail` (https://wiki.openstreetmap.org/wiki/Tag:railway%3Dlight_rail) isn't rendered at all. The rendering could be the same as for `railway=narrow_gauge`.

Thank you for the great style! :smile:

**Comment by der-stefan** [comment]
Hopefully fixed with 1af5d2d. But trams are really difficult to draw. Let's evaluate it, when the renderer shows it.
