### ISSUE TITLE
abandoned railways are rendered as active railways in garmin maps

### ISSUE THREAD

**Issue by max-dn** [der-stefan/OpenTopoMap#232]
As noted in the [OSM Forum](https://forum.openstreetmap.org/viewtopic.php?id=67733) it seems there is a problem with railway=abandoned in the garmin maps. These lines are rendered like active railways. (for example the [way 127716769](https://www.openstreetmap.org/way/127716769)).

**Comment by der-stefan** [comment]
Problem was solved long time ago. It is still not updated on the "old" server.
