### ISSUE TITLE
Question to copy to Garmin Device

### ISSUE THREAD

**Issue by gewillig** [der-stefan/OpenTopoMap#234]
All,
I've successfully installed some maps on my PC.
However, my German isn't that good, so I was wondering what files I need to copy to my SD card.
It says something the following : Die beiden Image-Dateien (OpenTopoMap-Länderkarte und Höhenlinien)
In the download I have from Germany, I have : OpenTopoMap-Germany.img and Contours.img
But for France I have OpenTopoMap-France.img and also a Contours.img

I guess there wound be an issue since the contour files have the same name ?

**Comment by gewillig** [comment]
Ah wait ... my error ... downloaded the wrong files. I've downloaded "PC" version in stead of "Garmin"

**Comment by der-stefan** [comment]
Yeah, I renamed the downloads a few days ago so that it is more clear.
