### ISSUE TITLE
Best to not show centimetre precision for peaks

### ISSUE THREAD

**Issue by jidanni** [der-stefan/OpenTopoMap#245]
Best to not show centimetre precision for peaks.
Say 1234, not 1234.12
https://www.opentopomap.org/#marker=17/23.697171/121.092213
else covers up contours with non-important info.

**Comment by max-dn** [comment]
This style just shows, what is mapped (sometimes rounded but not intentionally), so if a peaks elevation is known [very very exactly](https://www.openstreetmap.org/node/32968760),  it trusts the mapper and [shows the mapped data](https://www.opentopomap.org/#map=17/42.29801/-3.05196).

**Comment by jidanni** [comment]
Fine. Then the contour lines might as well be
1540.000000000
1530.000000000
because they are certainly not anything other than that.

**Comment by der-stefan** [comment]
By the way: It is not so easy to print the integer part only. Internationally there are the separators "," and "." and to make it worse the point is used as a thousands-separator as in 2.962. That is the height of the Zugspitze which is clearly not 2 m high.
"Trust the mapper" is the attitude in OpenStreetMap.

**Comment by jidanni** [comment]
Then it is too bad that OSM just saves heights as a text string and not a number.

**Comment by der-stefan** [comment]
Exactly, all fields - both keys and values - are strings in OSM. If you have a typo and ignore the warning of your favorite editor, then there is a typo. But everyone is free to use own keys and values. OSM trusts the mappers...

**Comment by jidanni** [comment]
But still they are invalid strings, according to https://wiki.openstreetmap.org/wiki/Key:height .
