### ISSUE TITLE
Large GPX files cannot be shown

### ISSUE THREAD

**Issue by martinstingl** [der-stefan/OpenTopoMap#249]
When I try to import .gpx files larger than 1 MByte no data is shown on the map at all.
I don't know where the exact threshold is, the error is with all my files > 1MByte.

**Comment by max-dn** [comment]
There is a default limit in Leaflet.FileLayer with 1MByte. I changed it to 8MByte (`L.Control.fileLayerLoad({ fileSizeLimit: 8196, ...`). Should work now and I hope this change has no negative side effects ;)

**Comment by martinstingl** [comment]
Perfect, works for me now.
Thank you!
