### ISSUE TITLE
error in map - erreur sur la carte

### ISSUE THREAD

**Issue by jeanmi007** [der-stefan/OpenTopoMap#264]
bonjour, je voudrais signaler une erreur,
une route interrompue de manière incorrecte: au nord-est de Ordon des Grands Bois
voir pièce jointe

merci de m'avoir lu

![Ordon des Grands Bois](https://user-images.githubusercontent.com/74345115/98907592-577b8b80-24bf-11eb-8b49-bd232c37fae5.png)

**Comment by martinstingl** [comment]
Hi, 
this is not the right place for reporting errors in the OSM data.
You can use OSM notes to report this:
https://wiki.openstreetmap.org/wiki/FR:Notes

**Comment by der-stefan** [comment]
Thanks for the explanation, @martinstingl
