### ISSUE TITLE
Churches do not get church symbol in map

### ISSUE THREAD

**Issue by KlaasDerFriese** [der-stefan/OpenTopoMap#279]
Hello,

I have  observed following behaviour:
Churches with OSM tag religion=christian and denomination=lutheran get the church symbol (circle with cross on top) in the map
but
Churches with OSM tag religion=christian and denomination=reformed **don't** get the church symbol (circle with cross on top) in the map
So a lot of churches in the western part of East Frisia do not get the church symbol as these are reformed.

I think all churches with religion=christian should get the church symbol in the map.

Best regards
Klaas

**Comment by max-dn** [comment]
There is allready a Pull Request for denomination=reformed: #278

**Comment by der-stefan** [comment]
Should be fine now. As @KlaasDerFriese did not add an example, I assume our fix did fix it. :-)

**Comment by der-stefan** [comment]
Should be fine now. As @KlaasDerFriese did not add an example, I assume our fix did fix it. :-)
