### ISSUE TITLE
Ireland-And-Northern-Ireland map is 0 bytes

### ISSUE THREAD

**Issue by EauBureau** [der-stefan/OpenTopoMap#289]
The `Ireland-And-Northern-Ireland` (2021-04-09 09:27:42) [on the download page](https://garmin.opentopomap.org/#ireland_and_northern_ireland) is 0 bytes. And there is no gmap at all.

**Comment by EauBureau** [comment]
Anyone? :confused:

**Comment by der-stefan** [comment]
The problem was the limited number of characters of Garmin maps. Fixed only after 1 year. That's a new record.

**Comment by EauBureau** [comment]
Thank you :smiley:
