### ISSUE TITLE
Api GPS

### ISSUE THREAD

**Issue by RumoEL** [der-stefan/OpenTopoMap#292]
Is it possible to get an array containing links to png based on the desired gps position and radius ?

get host/gps=$gps&r=3km

answ:
{
https: //host/4/5/4.png,//with gps coord in center
https: //host/4/5/5.png,//with gps coord in center
https: //host/4/5/6.png,//with gps coord in center
https: //host/4/5/7.png//with gps coord in center
...
}

**Comment by der-stefan** [comment]
https://wiki.openstreetmap.org/wiki/Slippy_map_tilenames
