### ISSUE TITLE
Garmin: MapInstall fails to install downloaded map from Spain

### ISSUE THREAD

**Issue by chrpinedo** [der-stefan/OpenTopoMap#30]
I downloaded http://garmin.opentopomap.org/data/spain/OpenTopoMap-Spain.exe. After installation, I can use the map in BaseCamp. However, whenever I try to send the map to de Garmin Etrex Legend HCx by using MapInstall, it fails.

MapInstall begin to build the map that is going to be sent to the garmin device and before begin the transmission the build process fails and MapInstall shows me a "Data were not sent right" message.

Any idea?

**Comment by der-stefan** [comment]
Please copy the files directly to your microSD card via an external card reader.
