### ISSUE TITLE
icons/textures reuse

### ISSUE THREAD

**Issue by severak** [der-stefan/OpenTopoMap#31]
it's possible to reuse your icons/textures for purpose of [my own project](https://www.openstreetmap.org/user/Sever%C3%A1k/diary/37681)?

if it's possible, under which license?

**Comment by der-stefan** [comment]
All icons and graphics are drawn to 100% on our own. Of course it is possible to re-use them. The license is CC-BY-SA, so please add a note in your license or description of your project.
