### ISSUE TITLE
File size *canada* is larger than 4Gb

### ISSUE THREAD

**Issue by ygamache** [der-stefan/OpenTopoMap#313]
The last update to the maps caused the Garmin file for Canada to exceed 4Gb in size and this cannot be copied over to a fat32 formatted SD card.

https://garmin.opentopomap.org/north-america/canada/otm-canada.zip

Thanks for correcting this.

**Comment by der-stefan** [comment]
Thanks for reporting. I reduced the resolution of the hillshade. Let's see if that was sufficient. The Canada file should be rebuilt on Saturday - just hang on.

**Comment by ygamache** [comment]
> Thanks for reporting. I reduced the resolution of the hillshade. Let's see if that was sufficient. The Canada file should be rebuilt on Saturday - just hang on.

The new file size is 3,27Gb, well below the 4Gb limit.
Thank you very much.
