### ISSUE TITLE
UTM Grid option

### ISSUE THREAD

**Issue by rui00rodrigues** [der-stefan/OpenTopoMap#32]
Is it possible to include a UTM or Lat/long Grid option on topo maps?

**Comment by der-stefan** [comment]
Yes, it is already possible to enable a grid. But for special grids we would need a leaflet plugin. If someone writes it, we would immediately include it.

**Comment by rui00rodrigues** [comment]
Do you mean that I can view it on opentopomaps.org website? I can't find it...

**Comment by der-stefan** [comment]
It can be activated in that options box in the top right corner. It is called "Gradnetz". So perhaps this could be a good start to develop a better grid? As I mentioned early, I don't have the ambition to do this, at least in the moment.

**Comment by der-stefan** [comment]
Now a Maidenhead Locator grid can be overlayed. Closing issue.

**Comment by rui00rodrigues** [comment]
Thanks for Maidenhead Locater Grid.
Now the UTM grid (Gradnetz) is not available. Can that cohabit with QTH Locater?
