### ISSUE TITLE
Garmin: lines are wrong and weird 

### ISSUE THREAD

**Issue by sikmir** [der-stefan/OpenTopoMap#328]
On the first screen is OTM slippy map, on the second screen is OTM Garmin map. Why all lines on Garmin map are "twisted"?
* I've tried to view the map on Garmin device as well - the same result.
* I've even tried to build Garmin map from source (following [instruction](https://github.com/der-stefan/OpenTopoMap/blob/master/garmin/README.md)) - again, the same wierd result.

![scr](https://user-images.githubusercontent.com/688044/190687418-539b5421-d5d0-40cd-a194-1eb916cad5c9.jpg)

**Comment by tomass** [comment]
As far as I know garmin format coordinate precision is quite low - all vertexes are snapped to a grid.

**Comment by sikmir** [comment]
> As far as I know garmin format coordinate precision is quite low - all vertexes are snapped to a grid.

Wow, didn't know that! I'm really surprised.
