### ISSUE TITLE
Area style for parks

### ISSUE THREAD

**Issue by gormo-osm** [der-stefan/OpenTopoMap#33]
Parks could be rendered with a light green area fill, or something similar to landuse=grass areas.

See area from opentopomap.org http://opentopomap.org/#map=15/52.38168/9.71359
and from openstreetmap.org http://www.openstreetmap.org/#map=15/52.38168/9.71359 .

Parks are a significant feature that are valuable to orientation on a map.

**Comment by der-stefan** [comment]
Good idea. I will implement it.
