### ISSUE TITLE
contour lines are missing 

### ISSUE THREAD

**Issue by a14stoner** [der-stefan/OpenTopoMap#338]
Hi, 
I am rendering a map with DEMs from here: https://e4ftl01.cr.usgs.gov/ASTT/ASTGTM.003/2000.03.01/ --> ASTER DEMs from 2019. 

I followed the tutorial from here: https://github.com/der-stefan/OpenTopoMap/blob/master/mapnik/HOWTO_DEM.md

The result is the following: 

![image](https://user-images.githubusercontent.com/59861665/216005591-43ffe389-53ea-47e3-ad73-b75e86a92237.png)

All is good except the contour lines are missing.
I imported everything according to the tutorial.

took warp-90.tif > converted it to a pbf > imported it with osm2pgsql

No errors when renderingit but the contour lines are missing
Here is an example of one database entry:

![image](https://user-images.githubusercontent.com/59861665/216005878-a9daccc9-8113-4d89-a647-70da91749d56.png)

I changed nothing at the opentopomap.xml or in the styles-otm/contours.xml. 
Here a little part from opentopomap.xml: 

```
<Layer name="contours">
    <StyleName>contours</StyleName>
    <Datasource>
        <Parameter name="table">(SELECT way,ele FROM planet_osm_line) AS contours </Parameter>
        <!--<Parameter name="table">(SELECT way,ele FROM contours) AS contours </Parameter>-->
        <Parameter name="dbname">contours</Parameter>
        <Parameter name="type"><![CDATA[postgis]]></Parameter>
        <Parameter name="host"><![CDATA[postgis]]></Parameter>
        <Parameter name="port"><![CDATA[5432]]></Parameter>
        <Parameter name="password"><![CDATA[]]></Parameter>
        <Parameter name="user"><![CDATA[gis]]></Parameter>
        <Parameter name="estimate_extend"><![CDATA[false]]></Parameter>
        &postgis-settings;
        </Datasource>
</Layer>
```
As you can see i use the table planet_osm_line. 

Thanks in advance.

**Comment by sletuffe** [comment]
To build your contour lines, you are using : https://github.com/der-stefan/OpenTopoMap/blob/master/mapnik/README.md 
with the phyghtmap + pbf + osm2pgsql  tool ?

Well, I've not used this step, I prefered the more common gdal_contour tool, it can open a tif DEM file and insert directly into postgres the resulting contour lines in one step.

**Comment by a14stoner** [comment]
Okay then ill try it this way and report back the results ;) thank you

**Comment by sletuffe** [comment]
And you might or might not be interested, but I have an PostgreSQL dump of worldwide contours (It saves me a lot of pain every time I want to re-import my db)
It is based on a mix or SRTM and ASTER, in the EPSG:3857 projection.
https://maps.refuges.info/download/

It was generated during dozen of hours with a command like the one you used (but with -i 10 : you are too greedy !)

**Comment by a14stoner** [comment]
ohh ! nice to know! ill try it by myself before - it it doesnt work ill use your dump! THANKS!!!

**Comment by a14stoner** [comment]
Okay i imported it with gdal_contours with -i 10 because it took so long. 
I had to rename the colum wbk_geometry to ele because the column is named like this in the opentopomap.xml. 

The result is the following: 

![image](https://user-images.githubusercontent.com/59861665/216089328-5c842c70-8353-484d-91de-98dc0c55ec2c.png)

no contours lines... can it be that the styles or even the opentopomap.xml is wrong? i made no other changes in the file...

**Comment by sletuffe** [comment]
Hard to guess what's wrong.

Check that your contour lines in PG are good :
select ele,st_astext(way) from contours limit 10 ?

Is it empty ? Is the projection the expected spherical mercator EPSG:3857 ?

**Comment by a14stoner** [comment]
I think i found the problem, 

when importing the data with gdal_contours the field wkb_geometry is the field way. But i dont have the values for the field ele. so the filters dont work.

**Comment by a14stoner** [comment]
Another thing i tried 

1. removing filters from styles-otm/contours.xml
2. Renaming wkb_geometry to way
3. Adding column ele to contours table

![image](https://user-images.githubusercontent.com/59861665/216275760-98b91e7d-1c6d-45a6-8759-8b014864915b.png)

now they are here. to just importing it with gdal_contours is not enough. 
@sletuffe did you always import it with gdal_contours and it worked out of the box?

**Comment by sletuffe** [comment]
> ogc_fid, id, wkb_geometry (which i renamed to ele).

That's a first problem :
ele stands for "elevation" : it should hold the elevation of the line.
The geometry of the (multi-) polyline being in the wkb_geometry column.
For some reason I don't remember, mine is renamed to "geom" but I think you can rename the column to the one in the opentopomap.xml

**Comment by sletuffe** [comment]
> ogc_fid, id, wkb_geometry (which i renamed to ele).

That's a first problem :
ele stands for "elevation" : it should hold the elevation of the line.
The geometry of the (multi-) polyline being in the wkb_geometry column.
For some reason I don't remember, mine is renamed to "geom" but I think you can rename the column to the one in the opentopomap.xml

**Comment by sletuffe** [comment]
As a side note : You seam to allways show screen captures of an openlayer slippy map, wich mean that you most likely need to :

**Comment by sletuffe** [comment]
\o/

You are right, understanding what is behind the scene makes it easier to later understand the possible problems.

But some times downloading preprocess data that takes aaaaages to generate is also a good way to save time that others have spent :-)
While still knowning what was needed to do it.
