### ISSUE TITLE
Server offline?

### ISSUE THREAD

**Issue by reilem** [der-stefan/OpenTopoMap#355]
Server hosted at https://opentopomap.org is no longer responding. Has it maybe been moved or is it down for maintenance? Thanks.

**Comment by StellarStoic** [comment]
It's been 2 days (28.01) since the issue started

**Comment by gbay27** [comment]
My firefox is complaining that there's an issue with the website's configuration... Very likely the https/TLS certificate has expired.

**Comment by Jelfff** [comment]
Thanks for switching.  All looks good now.

**Comment by reilem** [comment]
Server is back online now 👍
