### ISSUE TITLE
Mouse Pointer not visible in map area under Win 11

### ISSUE THREAD

**Issue by hoerni1000** [der-stefan/OpenTopoMap#361]
When I move the mouse over the map area the mouse pointer (handsymbol) is not visible. On OpenStreetMaps there`s no issue, only on OpenTopoMap.
Operating System: Win 11
Browser: Reproducable on Chrome and Edge

Is this a known issue?

**Comment by fortchagos** [comment]
I have no issue in Brave, Opera, Edge, or Chrome on Windows 10 or Windows 11.  Graphics card issue maybe?  Windows restart (first step to fixing anything on Windows)?

**Comment by hoerni1000** [comment]
Restart does not help - issue is permament.

**Comment by hoerni1000** [comment]
Looks like it it works in Firefox (to go) - only in Edge and Chrome I cannot see the mouse pointer, but I cannot find the right Chrome setting which causes this behaviour.

**Comment by hoerni1000** [comment]
Issue was automatically solved by newest Windows 11 Insider Preview 10.0.26080.1100 (ge_release) update. Issue can be solved.
