### ISSUE TITLE
garmin.opentopomap.org down

### ISSUE THREAD

**Issue by chenseanxy** [der-stefan/OpenTopoMap#370]
Hi! The Garmin site seems to have been down for a while.

This project had been extremely helpful for all my previous trips, so let me know if there's a way to support (I can help host too for example).

**Comment by paulo-olx** [comment]
Same here, I can offer support if needed, tnx!

**Comment by paulooliveira** [comment]
Same here, I can offer support if needed, tnx!

**Comment by afgb1977** [comment]
Hello, I came here with the intention of indicating that the garmin .img download site has stopped working
Anything we can do to help get the site back online?

**Comment by afgb1977** [comment]
Garmin .img download platform working again.
Thank you so much.

**Comment by chenseanxy** [comment]
Seems like the site is up again, closing this
