### ISSUE TITLE
HOWTO_Server clarification

### ISSUE THREAD

**Issue by WillieMaddox** [der-stefan/OpenTopoMap#40]
In the file, HOWTO_Server, the paths to flat-nodes are different. Should they be the same?

\# Load data into database

screen osm2pgsql --slim -d gis -C 12000 --number-processes 10 --flat-nodes **/mnt/db/flat-nodes/gis-flat-nodes.bin** --style ~/OpenTopoMap/mapnik/osm2pgsql/opentopomap.style ~/data/planet-latest.osm.pbf

\# Update data

osm2pgsql --append --slim -d gis  -C 12000 --number-processes 10 --flat-nodes **~/data/flat-nodes.bin** --style ~/OpenTopoMap/mapnik/osm2pgsql/opentopomap.style ~/data/updates/changes.osc.gz

Thanks,

**Comment by der-stefan** [comment]
Yes, of course. The flat-nodes file is some kind of external index file, so you have to always update it. Some guides about osm2pgsql tell you to use it.
