### ISSUE TITLE
how to merge OpenStreetMap &  SRTM-Höhendaten

### ISSUE THREAD

**Issue by biopilz** [der-stefan/OpenTopoMap#42]
for older garmin gpsmap60csx

ideally could YOU do it?

**Comment by der-stefan** [comment]
It is not planned to do that, since switchable contour lines are a very nice feature on newer Garmins. You can merge the contours into the map on your own with GMapTool.

**Comment by biopilz** [comment]
danke für antwort! thomas
> Stefan Erhardt <notifications@github.com> hat am 25. Juni 2016 um 23:11
> geschrieben:
> 
> 
> It is not planned to do that, since switchable contour lines are a very nice
> feature on newer Garmins. You can merge the contours into the map on your own
> with GMapTool.
> 
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/der-stefan/OpenTopoMap/issues/42#issuecomment-228570670

--
http://biopilz.wordpress.com
