### ISSUE TITLE
Be explicit about the license

### ISSUE THREAD

**Issue by nebulon42** [der-stefan/OpenTopoMap#46]
This repository has no license file attached to it.

On the website I found:

> OpenTopoMap steht unter der Lizenz CC-BY-SA. Das bedeutet, dass die Karte kostenlos und frei verwendet werden darf, solange stets Namensnennung erfolgt und die Weitergabe unter gleichen Bedingungen möglich ist.
> 
> Der Kartenstil steht unter der gleichen Lizenz und ist über Github abrufbar.

It would be good to be explicit about the license here on GitHub to avoid hassle and confusion (cf. current discussion Mapbox vs. OSM2VectorTiles).

**Comment by der-stefan** [comment]
The license is CC-BY-SA for everything except the Garmin files: They are only CC-BY-NC-SA, as we have no interest in upsetting Garmin Ltd.

**Comment by nebulon42** [comment]
Ah, what I really meant is to write this into a file named LICENSE or similar as can be found with many FOSS projects here on GitHub. Sorry for being not clear on this.
