### ISSUE TITLE
Please add train station naming

### ISSUE THREAD

**Issue by pgavrilov** [der-stefan/OpenTopoMap#51]
OpenTopoMap render engine shows stations but not station names.

![opentopomap train stations](https://cloud.githubusercontent.com/assets/3817702/18579669/c7b226ce-7bff-11e6-8a2c-1ad2df8cbf27.jpg)

**Comment by der-stefan** [comment]
https://opentopomap.org/#marker=14/55.80977/37.94764

Bug is fixed. But train stations are only rendered if the tag "train=yes" exists. This is to distinguish train stations from subway stations.
