### ISSUE TITLE
Render sac_scale, via_ferrata, via_ferrata_scale and ref for tracks and paths

### ISSUE THREAD

**Issue by Ircama** [der-stefan/OpenTopoMap#66]
First of all congratulations for this great map!

Considering that traditional touristic topographic maps generally show mountain routes giving indication of difficulty, I’d like to check whether you are considering to render [`sac_scale`](http://wiki.openstreetmap.org/wiki/Key:sac_scale) for [`highway=path`](http://wiki.openstreetmap.org/wiki/Tag:highway%3Dpath).

Would it be possible to add [`via_ferrata`](http://wiki.openstreetmap.org/wiki/Proposed_features/via_ferrata), `via_ferrata_scale` and `sac_scale` to [opentopomap.style](https://github.com/der-stefan/OpenTopoMap/blob/master/mapnik/osm2pgsql/opentopomap.style)?

If I’m not wrong, I also see that [`text-roads-ref`](https://github.com/der-stefan/OpenTopoMap/blob/master/mapnik/styles-otm/text-roads-ref.xml) is also not used for `highway=path` and [`highway=track`](http://wiki.openstreetmap.org/wiki/Tag:highway%3Dtrack). Would it be useful to add this?

Thanks

**Comment by mboeringa** [comment]
Cross reference for potentially interesting discussion on Carto:
https://github.com/gravitystorm/openstreetmap-carto/issues/1500

And some example rendering:
https://github.com/gravitystorm/openstreetmap-carto/issues/1500#issuecomment-96587116

**Comment by max-dn** [comment]
If it is possible to add via_ferrata, via_ferrata_scale and sac_scale:

I would suggest to render just 2 or 3 different kinds of pathes: "easy ways", "difficult ways" and maybe "ferratas". More than 3 different lines will be confusing.

1. a "easy way" is a highway=path & sac_scale=NULL, T1-3
2. a "difficult way" is a highway=path & sac_scale=T4-6
3. a "difficult way" is a highway=path & via_ferrata_scale=1
4. a "ferrata" is a highway=path & via_ferrata_scale=NULL, 2-6
5. a "ferrata" is a highway=via_ferrata 

(3.+4. because I know a lot of pathes which are normal walking pathes and got an short steel cable in the last years. In times of event oriented tourism marketing every valley needs a "ferrata [x]" checkbox)

Maybe its even enough to render two types, "easy" and "difficult and ferrata" to show "there you can walk" or "read a guidebook first".

**Comment by keenonkites** [comment]
Agreed that too many lines is not really helpfull, less is more.
But:

Putting a "ferrata" into a non "ferrata" category as proposed by Max with 3. might be dangerous as "ferratas" need proper preparation and most of the time also proper equipment.

The distinction between 1 and 2 is also "questionable": T3 can be definitely more than easy and it suggest that someone can just go and have a strawl on such a way.

I would rather suggest to have the same categories as the 'labeling' on the hiking signs in Switzerland:
1) 'easy': T1: orange signs
2) 'middle': T2-T3: white-red-white signs
3) 'hard': T4-T6: white-blue-white
4) 'ferrata': everything labled as ferrata

Going into more details in the ferratas is in my opinion not needed:
- if it's a ferrata you have to consult proper route descriptions anyway
- as ferratas are normaly in steep or very steep (if not vertical) area they probably have/give a wrong impression on maps, even when one is also considering the elevation.

**Comment by max-dn** [comment]
ok, forget 3. ;)

Having 4 types of pathes will be difficult. More colors could help, but I think a reduced use of colors and a rather thin rendering of pathes are important for this stile. Solid and dashed lines are used for tracks, so we only can vary width and spacing of dotted lines (or use cross hairs like in mboeringa's example).

**Comment by der-stefan** [comment]
Yes, I agree with @max-dn: The OpenTopoMap style should be similar to the good old official German map style. This style is quite black/white. I have no idea how they render alpine paths. Does someone have a old TK50 of southern Bavaria and scan it?

**Comment by mboeringa** [comment]
Are they actually included on these maps?... This TK50 legend from Baden-Württemberg does not show any entry for this type of path:
https://www.lgl-bw.de/lgl-internet/web/sites/default/de/07_Produkte_und_Dienstleistungen/Galerien/Dokumente/Legende_TK50.pdf

[This particular map](http://www.berghotel.com/CustomerData/201/Files/Images/tours/karte-tofana-di-rozes.jpg) from what appears to be an official Italian map series is one of the few real examples showing via ferratas from a superficial Google search.

**Comment by max-dn** [comment]
> Does someone have a old TK50 of southern Bavaria and scan it?

Old TK25 you can see on [bayernatlas](https://geoportal.bayern.de/bayernatlas/). Its a little bit hidden ("Thema Wechseln" -> "Geobasisdaten" -> "Historische Karten" -> "1:25000" activates an overlay and klicking on the map opens a chooser with some scanned TK25 from 1950-2007).

These maps have 2 kinds of pathes: "Fußweg" and "Pfadspur, Klettersteig" [example 1990](http://www.geodaten.bayern.de/histTopoKarten/02_TK25/02_8532_S_1990.pdf]. The second ones are something like "sac_scale>3 or via_ferrata_scale>0 or path_visibility<bad" in terms of OSM.

They were rendered like "------" for "Fußweg" and "---  ---" for "Pfadspur, Klettersteig" and on some maps its seems the map painter was free to vary the spaces "---      ---" to express difficulty. 

Maybe something like ".......", "...  ..." and "..  .."?

**Comment by der-stefan** [comment]
> Old TK25 you can see on bayernatlas. Its a little bit hidden ("Thema Wechseln" -> "Geobasisdaten" -> "Historische Karten" -> "1:25000" activates an overlay and klicking on the map opens a chooser with some scanned TK25 from 1950-2007).

Dankeschön! This is fantastic! I did not know, they scanned the old TK25...

We can - of course - deviate from the TK25 map style, but should keep its spirit. I think it is a good idea of @max-dn with the different dashing or dotting. The challenge is that the paths are well visible.

**Comment by max-dn** [comment]
I need some feedback about my first rendering tests...

Thumb rule: 
* If there are gaps between the dots, the path is not easy
* If you have problems to see the path on the map, maybe you won't find it on the ground.

Detailed rules: 
* pathes with sac_scale=T1-2 and via_ferrata_scale=0 are rendered like now (dots, no gap)
* sac_scale=T3-4 and via_ferrata_scale=0: 3 dots and a gap
* sac_scale=T5-6 and via_ferrata_scale=0: 2 dots and a longer gap
* highway=via_ferrata or via_ferrata_scale>0: 2 dots and a longer gap
* trail_visibility<="bad": 50% to 60% opacity

Ferratas and T5-6 have different rules, but are rendered in the same style. I didn't find a 4th morse code for a 4th class of ways and maybe thats ok. This map doesn't want to be a alpine hiking map and "gaps -> its not easy, long gaps -> you really must get more information" is enough.

The classifications T12/T34 are near to german topo maps. It's not like keenonkites suggestion "T1/T23/T456" like on signs, but I think the step from T1 to T2 is less important than T2-T3 (a matter of taste: T1 to T2 is "you may fall down", T2 to T3 is "you may need your hands"...)

Some examples (only zoom 15-16 available in a small area, there is a link to osm.org in the right bottom if you want to see the data)
[northern part T2, then T5, then T4 to west](https://geo.dianacht.de/otmtest/sac1.html?zoom=16&lat=47.4157&lon=11.13401&layers=B000)
[a mix of all kind of pathes](https://geo.dianacht.de/otmtest/sac1.html?zoom=16&lat=47.42681&lon=11.04222&layers=B000)
[a mix of visible and unvisible pathes](https://geo.dianacht.de/otmtest/sac1.html?zoom=15&lat=47.41058&lon=11.38529&layers=B000)
[invisible pathes in the woods](https://geo.dianacht.de/otmtest/sac1.html?zoom=15&lat=47.56484&lon=11.17663&layers=B000)
[all kind of pathes in scree and wood](https://geo.dianacht.de/otmtest/sac1.html?zoom=16&lat=47.42494&lon=11.45842&layers=B000)

**Comment by der-stefan** [comment]
The pull request by @max-dn was accepted and the renderer should render the style now (may take some time for your tiles...). You can use this issue for further discussion if necessary.

**Comment by Ircama** [comment]
Just wish to thank @der-stefan, @max-dn and all involved.
