### ISSUE TITLE
Adding .MD extension to howto

### ISSUE THREAD

**Issue by Ircama** [der-stefan/OpenTopoMap#67]
I'm just reading the *howto* documents available in this repository and I am verifying that they are in Markdown format: I would suggest to add the .MD extension, to allow them to be rendered by GitHub.
If there is not a specific reason to keep them as they are, I can add a pull request with these changes.

**Comment by der-stefan** [comment]
Oh really? The howto files are not written wittingly in Markdown format. There are problems with the # as the letter to start a comment. And the indentation is not four spaces, but one tab.
