### ISSUE TITLE
mapnik/HOWTO_DEM documentation issues

### ISSUE THREAD

**Issue by ktye** [der-stefan/OpenTopoMap#71]
mapnik/HOWTO_DEM:

Line:21 cannot be done with a normal user account
$ sudo -u postgres -i

Line:25: psql -c 'GRANT .... TO tirex;' fails with role "tirex" does not exist.
Should it be created before with:
$ psql -c 'CREATE ROLE tirex;'
Or is this done by a dependency package, which didn't work for me?

Line:26: psql -d contours -c "CREATE INDEX contours_geohash ON contours ... fails with relation "contours" does not exist.
I don't know, if I'm on the right track...

**Comment by der-stefan** [comment]
Are you using Ubuntu? You need to be able to create databases and read and write from that database. You can do this differently and there is no trick done for this contours database. I think the best for you is to get familiar with postgresql and user permissions.

**Comment by m-dp** [comment]
Hi, may I note that the user does not only have an issue with permissions? Please note below: 

Line:26: psql -d contours -c "CREATE INDEX contours_geohash ON contours ... fails with relation "contours" does not exist.

The database 'contours' does not contain table 'contours'
