### ISSUE TITLE
tile.conf missing?

### ISSUE THREAD

**Issue by int19h** [der-stefan/OpenTopoMap#72]
Per [installation instructions](https://github.com/der-stefan/OpenTopoMap/blob/0725e03999d0ebc6d62c5cc7837cdd225efda001/mapnik/HOWTO_Ubuntu_16.04#L90):

> copy conf/tile.conf into /etc/apache2/mods-available/tile.conf

But where does `tile.conf` come from? There's no such file (and, indeed, no directory `conf`) anywhere in `~/src` at that point (including any subdirectories).

**Comment by der-stefan** [comment]
You are right, the config files are missing. They are too specific for my system.

**Comment by der-stefan** [comment]
Ok, this is my configuration:
```
# /etc/apache2/mods-available/tile.conf

ModTileRenderdSocketName /var/lib/tirex/modtile.sock
ModTileTileDir           /mnt/tiles
ModTileRequestTimeout    5

AddTileConfig            / opentopomap
```
