### ISSUE TITLE
Hiking and cycling routes

### ISSUE THREAD

**Issue by hdevillepoix** [der-stefan/OpenTopoMap#75]
Beautiful map!!
Is there a plan to include hiking and cycling routes relations?
Maybe a bit like what is done on the higher zoom levels of opencyclemap/outdoors? (eg. http://opencyclemap.org/?zoom=15&lat=-32.7598&lon=116.25751&layers=000B0)

**Comment by der-stefan** [comment]
Thanks! Hiking and cycling routes are not planned to be included in the map style. But you can already add transparent overlays via our web interface! Look for the two Lonvia layers in the layer switcher.
