### ISSUE TITLE
Viewpoint directions

### ISSUE THREAD

**Issue by der-stefan** [der-stefan/OpenTopoMap#77]
The direction of viewpoints should be rendered as already described some time ago in the OSM Forum (German):
https://forum.openstreetmap.org/viewtopic.php?pid=261496#p261496

The process should be as simple as possible...

**Comment by mboeringa** [comment]
A nice test area is Budapest:
http://www.openstreetmap.org/#map=18/47.49522/19.04141
![directional_viewpoints](https://cloud.githubusercontent.com/assets/7635726/22033708/dbcf1eb4-dce9-11e6-8068-674ce2150b85.jpg)

**Comment by der-stefan** [comment]
Double issue.
