### ISSUE TITLE
OpenTopoMap: aeroway=runway

### ISSUE THREAD

**Issue by keenonkites** [der-stefan/OpenTopoMap#85]
There are two different versions of mapping them, either as way (line) or as area (closed way) with the additional tag area=yes. There are even cases where both is done normal way (line) as well as closed line (are) with area=yes tag.
There seems to be a dispute about this and both versions are possible and used.
Only the version without area=yes is properly shown on the OpenTopoMap.

An example for a runway with area=yes is (not showing properly):
http://www.openstreetmap.org/way/152401123

An example for a runway not tagged as area (showing properly):
http://www.openstreetmap.org/way/25214303

As both versions of tagging are quite common, it probably makes sense to cover both in the OpenTopoMap.

Cheers Patrik

**Comment by max-dn** [comment]
Do not know much about airports. Is it ok, to render render grey areas where aeroway=(apron, helipad, runway, taxilane, taxiway) in zoom level >=12?
A lot of runways are mapped twice ([example](https://www.openstreetmap.org/#map=17/47.80367/12.99571)) with runway-lines inside runway-areas. Does it make sense to show the lines or should the area hide them?

**Comment by keenonkites** [comment]
Max,
I'm also not the runway specialist. I assume you could take the default osm style to check how it is done as my examples are both showing up properly on openstreetmap default.

In my opinion the area can hide a potential existing underlaying line as it is redundant information if it's mapped double.... and the area shows the form more precicely than just the straight line.
Resolution? I would guess it should be shown at the same level as the lines are shown up now.
Thanks and regards
Patrik

**Comment by severak** [comment]
In my [Metropolis style](https://www.openstreetmap.org/user/Severak/diary/39521) I draw firstly line-based runways and later area-based runways. It seems to work.

**Comment by keenonkites** [comment]
I've noticed new commits regarding this... thanks.
How long does it take until the tiles are re-renedered ?
.... question comes as my initial 'problemcase' is still not showing up properly:
http://www.openstreetmap.org/way/152401123

Thanks
Patrik

**Comment by max-dn** [comment]
Some weeks and then some days...

At first Stefan has to close the request, then tiles are rendered and after some days we will see it. He hast no time the next weeks. I just made the request now, because I am also busy til April. The images in the request are made with a local copy of the stile.

Max

**Comment by keenonkites** [comment]
thanks for the feedback.
There's no hurry and no stress at all... just wondered... ;-)
Thanks for handling it anyway. So I'll wait until issue is closed and start to recheck 'some days' after it.
Cheers Patrik

**Comment by der-stefan** [comment]
@keenonkites: Thank you for the bug report! With the fix done by @max-dn, your example shows correctly: https://opentopomap.org/#map=15/-25.59585/-54.48322

**Comment by keenonkites** [comment]
Thanks, guys.
Looks much better now.
Cheers
Patrik
