### ISSUE TITLE
piers aren't areas

### ISSUE THREAD

**Issue by kvlahromei** [der-stefan/OpenTopoMap#87]
Hi,
while the style looks pretty professional, I noticed an small issue with handling the man_made=pier elements. For example [here in Rostock](https://opentopomap.org/#map=16/54.09506/12.12670):
![opentopomap issue pier rostock](https://cloud.githubusercontent.com/assets/8177370/23551586/b28d155a-0017-11e7-8036-7a97a0e26631.jpg)

The pier network seems to be threatened as filled white polygon, which makes IMHO no sense?

**Comment by max-dn** [comment]
I made a patch, but we have to patient. First it hast to be accepted and merged 

Max

**Comment by der-stefan** [comment]
Thank you, @kvlahromei for the bug report and @max-dn for the patch! It is fixed now.
