### ISSUE TITLE
garmin.opentopomap.org: map of Uzbekistan

### ISSUE THREAD

**Issue by Alexandr0777** [der-stefan/OpenTopoMap#93]
Hello!
Could you add a map of Uzbekistan for Garmin navigators?

Best regards,
Alexandr

**Comment by der-stefan** [comment]
Hi Alexandr,
some day we will change the Garmin coverage to worldwide. Please don't ask, when...
Stefan

**Comment by Alexandr0777** [comment]
Thanks.
Maybe you could give recommendations on how to independently make a vector map of Uzbekistan based on openopomap.org data?
