### ISSUE TITLE
Render power infrastructure areas

### ISSUE THREAD

**Issue by max-dn** [der-stefan/OpenTopoMap#99]
Render power=generator/plant/substation like landuse=industrial if it's not a building.

Some power=* these are additional tagged with [landuse=industrial](http://www.openstreetmap.org/way/23802422#map=16/48.6052/12.2952) and [are shown light gray](https://opentopomap.org/#map=16/48.60535/12.29370). Others are not (like [this one](http://www.openstreetmap.org/way/77694915#map=17/48.58473/12.22004) in [OTM](https://opentopomap.org/#map=17/48.58519/12.22043))

Discussion in the german forum: https://forum.openstreetmap.org/viewtopic.php?pid=643941#p643941

**Comment by mboeringa** [comment]
**power=generator** should in fact actually always be some kind of building, as it refers to the generator itself, not the entire facility as **power=plant** encompasses.

In reality, there are quite a number of mistaggings, where users tag **power=generator** on the outline of the facility, which should be **power=plant**. Every time I encounter this, I correct it. I quickly spot these errors, as I use distinct rendering for generators in my personal style. If the entire plant looks like a generator, its wrong ;-)

power=substation can be both a building, or an outline of the facility.

**Comment by max-dn** [comment]
ok, so we just render plant and substation gray (if its not a building) and let generator as it is now (no rendering unless generator:source=solar which is light blue)?

**Comment by der-stefan** [comment]
Pull request was merged and looks good.
